name: Feature Request
description: Suggest a new architectural feature or plugin capability for Pytja.
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in expanding Pytja's architecture. Please provide detailed context for your request.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Architecture / Solution
      description: How should this feature work under the hood? (WASM integration, CLI command, etc.)
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or tools you've considered.
    validations:
      required: false